sudo: required
services:
  - docker

before_install:
  - docker build -t nagasaim227/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true nagasaim227/react-test npm test -- --coverage

after_success: 
  - docker build -t nagasaim227/multi-client ./client
  - docker build -t nagasaim227/multi-nginx ./nginx
  - docker build -t nagasaim227/multi-server ./server
  - docker build -t nagasaim227/multi-worker ./worker